### ISSUE TITLE
Error while train.py: loading "model.h5"

### ISSUE THREAD

**Issue by 0rShemesh** [Qerim-iseni09/Stock-Predictor-V4#3] opened 2023-05-26 14:04 UTC
**Describe the bug**
After epoch stage throw an error:
```
Traceback (most recent call last):
  File "/****/Stock-Predictor-V4/train.py", line 129, in <module>
    model = load_model("model.h5")
  File "/****/Documents/Stock-Predictor-V4/venv/lib/python3.10/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/****/Stock-Predictor-V4/venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/****/Stock-Predictor-V4/venv/lib/python3.10/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model.h5
```  

**To Reproduce**
#### install
1. create venv `python -m venv venv` 
2. source ./venv/bin/activate
3. chmod +x install.sh && ./install.sh 
4. enter sudo password when need
#### prepare
5.  Donwload csv from yahoo move the file to data/ 
6. modify `prepare_data.py` script from example.csv to my_stock.csv
7. run `python prepare_data.py`
8. run `python train.py`

**Expected behavior**
Finish `python train.py` without an errror

**Screenshots**
![image](https://github.com/Qerim-iseni09/Stock-Predictor-V4/assets/34350066/cdad1ed5-e1db-4174-b434-a2eeb617eadf)

**Desktop (please complete the following information):**
 - OS:6.1.29-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May 17 14:00:55 UTC 2023 x86_64 GNU/Linux  
 - Python: 3.10.10
 -  Working directory: Stock-Predictor-V4

**Additional context**

**Comment by lex-hue** [comment] 2023-05-26 14:29
Could you please update/upgrade your system and perform a `git pull` on the repository again before I can attempt to assist you? If you encounter any further issues, please follow these instructions:

If you prefer to set up the repository with a virtual environment (venv), kindly copy and execute the following commands:

```
git clone https://github.com/Qerim-iseni09/Stock-Predictor-V4.git
pip install venv
python -m venv Stock-Predictor-V4
cd Stock-Predictor-V4
source bin/activate # Execute this before using any script
./install.sh # Please disregard the two messages displayed
```

Alternatively, if you do not require a virtual environment, you can copy and execute these commands instead:

```
git clone https://github.com/Qerim-iseni09/Stock-Predictor-V4.git
cd Stock-Predictor-V4
chmod +x install.sh
./install.sh # Please disregard the two messages displayed
```

If any errors persist, please notify me again. If not, you can close this issue. Thank you for your support!

**Comment by 0rShemesh** [comment] 2023-05-26 14:46
Done!
Same error as before
@Qerim-iseni09

**Comment by lex-hue** [comment] 2023-05-26 14:48
Is there any model.h5 file saved?

**Comment by 0rShemesh** [comment] 2023-05-26 14:49
> Is there any model.h5 file saved?
@Qerim-iseni09

 
Nope

**Comment by Qerim-iseni09** [comment] 2023-05-26 14:49
Let me see here..

**Comment by lex-hue** [comment] 2023-05-26 15:05
Could you please verify the TensorFlow version you are using? I have tested the code with TensorFlow version 2.12.0 and Python 3.11.2.

**Comment by lex-hue** [comment] 2023-05-26 15:15
@0rShemesh 

Try the new commit by running `git pull` and tell me if the proplem still persists.

**Comment by 0rShemesh** [comment] 2023-05-26 15:24
Things I've done:
* Update to `Python 3.11.2`
* Validate that TensorFlow's version is 2.12.0
* did again clone and rebuild everything under venv

looks like new problem:
```
Can save best model only with val_loss available, skipping.
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
1/1 [==============================] - 1s 648ms/step - loss: 0.3228
Epoch 200/200
1/1 [==============================] - ETA: 0s - loss: 0.2731WARNING:tensorflow:Can save best model only with val_loss available, skipping.
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
1/1 [==============================] - 1s 652ms/step - loss: 0.2731

Test 1

Traceback (most recent call last):
  File "/*****/Stock-Predictor-V4/train.py", line 125, in <module>
    y_pred_test = model.predict(X_test)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/*****/Stock-Predictor-V4/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/*****/Stock-Predictor-V4/lib/python3.11/site-packages/keras/engine/training.py", line 2407, in predict
    raise ValueError(
ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```

**Comment by lex-hue** [comment] 2023-05-26 15:29
Ill look at it later okay?

Im getting busy rn and sorry for the inconviniance..

**Comment by lex-hue** [comment] 2023-05-27 11:11
After examining the situation, I find it quite interesting that the error doesn't occur on my side. I sincerely apologize, but I don't think there's much I can do to help you. Maybe you can try deleting the repository and starting the process again. Another option is to share your CSV file here, so I can investigate the error further. It's possible that certain data is missing or there are other similar factors involved. Please provide the CSV file so that I can test it alongside your data. After further analysis, it seems that you might be providing insufficient data for the learning process. Please download the data using the maximum setting in Yahoo.

**Comment by lex-hue** [comment] 2023-05-27 18:33
@0rShemesh 

Upon conducting tests, it became evident that the quantity of data provided was insufficient, resulting in the occurrence of errors. To resolve this, I kindly request you to revisit the download/generation process and obtain a minimum of two years' worth of data. Once this adjustment is made, the program should operate as intended. If this solution resolves the error and I have made the necessary corrections in my README.md file, please consider closing this issue.

**Closed as completed** 2023-05-27 21:46 UTC
Labels: bug, good first issue
